mixed-port: 7890
allow-lan: true
bind-address: '*'
geodata-mode: true
global-client-fingerprint: random
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver: [ 223.5.5.5, 8.8.8.8 ]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver: [ 'https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query', "quic://dns.adguard.com:784", "tls://223.5.5.5:853"]
  fallback: [ 'https://8.8.8.8/dns-query', 'https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query']
  fallback-filter: { geoip: true, ipcidr: [ 240.0.0.0/4, 0.0.0.0/32 ] }
rules:
  - DOMAIN-SUFFIX,bing.com,PROXY
  - DOMAIN-SUFFIX,openai.com,PROXY
  - DOMAIN-SUFFIX,bing.cn,PROXY
  - DOMAIN-SUFFIX,googleapis.com,PROXY
  - GEOSITE,category-ads-all,REJECT
  - DOMAIN-SUFFIX,appcenter.ms,REJECT
  - DOMAIN-SUFFIX,app-measurement.com,REJECT
  - DOMAIN-SUFFIX,firebase.io,REJECT
  - DOMAIN-SUFFIX,crashlytics.com,REJECT
  - DOMAIN-SUFFIX,google-analytics.com,REJECT
  - GEOSITE,cn,DIRECT
  - GEOIP,CN,DIRECT
  - GEOIP,LAN,DIRECT
  - MATCH,PROXY