- name: Remove tuic-server on managed nodes
  hosts: kvm
  become: true
  tasks:
    - name: Install certbot with package manager
      package:
        name: certbot
        state: latest
    - name: Tunic GET
      get_url:
        url: https://raw.githubusercontent.com/QIN2DIM/tuic-installer/main/tunic.py
        dest: /tmp/tunic.py
    - name: Tunic Remove
      command: "python3 /tmp/tunic.py remove -d {{ tunic_domain }}"
      register: remove_result
    - name: Check result of local deployment
      debug:
        var: remove_result.stdout_lines